@module external bandLogo: string = "./band-blue-circle-logo.png"
@module external searchIcon: string = "./search-icon.png"
@module external searchGray: string = "./search-gray.svg"
@module external rightArrow: string = "./right-arrow.svg"
@module external bg: string = "./bg.png"
@module external tickIcon: string = "./tick.svg"
@module external copy: string = "./copy.svg"
@module external loadingCircles: string = "./loading_circles.gif"
@module external success: string = "./success.svg"
@module external success2: string = "./success2.svg"
@module external fail: string = "./fail.svg"
@module external fail2: string = "./fail2.svg"
@module external pending: string = "./pending.svg"
@module external expired: string = "./expired.svg"
@module external unknown: string = "./unknown.svg"
@module external noRevisionIcon: string = "./noRevision.png"
@module external inactiveValidatorLogo: string = "./inactiveValidatorLogo.svg"
@module external activeValidatorLogo: string = "./activeValidatorLogo.svg"
@module external externalLink: string = "./externalLink.svg"
@module external leftAngle: string = "./left-angle.svg"
@module external graphBG: string = "./graph-bg.svg"
@module external notFoundBg: string = "./notFoundBg.svg"
@module external ethereumIcon: string = "./ethereum.svg"
@module external cosmosIBCIcon: string = "./cosmosibc.svg"
@module external kadenaIcon: string = "./kadena.svg"
@module external solidityIcon: string = "./solidity.svg"
@module external vyperIcon: string = "./vyper.svg"
@module external golangIcon: string = "./golang.svg"
@module external pactIcon: string = "./pact.svg"
@module external ibcLogo: string = "./ibcLogo.svg"
@module external ibcDirArrow: string = "./ibcDirArrow.svg"
@module external modalBg: string = "./modal-bg.svg"
@module external waitingModalBg: string = "./waiting-modal-bg.svg"
@module external ledgerStep1: string = "./ledger-step1.svg"
@module external ledgerStep2Cosmos: string = "./ledger-step2-cosmos.svg"
@module external ledgerStep2BandChain: string = "./ledger-step2-bandchain.svg"
@module external triangleDown: string = "./triangle-down.svg"
@module external sortDown: string = "./down-arrow.svg"
@module external closeButton: string = "./closeButton.svg"
@module external close: string = "./close.svg"
@module external menu: string = "./menu.svg"
@module external cmcLogo: string = "./coinmarketcap.svg"
@module external cmcWhiteLogo: string = "./coinmarketcap-white.svg"
@module external noBlock: string = "./no-block.svg"
@module external noAccount: string = "./no-account.svg"
@module external noSource: string = "./no-source.svg"

@module external noBlockDark: string = "./no-block-dark.png"
@module external noTxDark: string = "./no-tx-dark.png"
@module external noDelegatorDark: string = "./no-delegator-dark.png"
@module external noOracleDark: string = "./no-oracle-dark.png"
@module external noDataDark: string = "./no-data-dark.png"

@module external noBlockLight: string = "./no-block-light.png"
@module external noTxLight: string = "./no-tx-light.png"
@module external noDelegatorLight: string = "./no-delegator-light.png"
@module external noOracleLight: string = "./no-oracle-light.png"
@module external noDataLight: string = "./no-data-light.png"

// HomePage
@module external bandToken: string = "./band-token.svg"
@module external bgLeftLight: string = "./bgleft-light.png"
@module external bgLeftDark: string = "./bgleft-dark.png"

// Footer
@module external githubSvg: string = "./github.svg"
@module external mediumSvg: string = "./medium.svg"
@module external twitterSvg: string = "./twitter.svg"
@module external telegramSvg: string = "./telegram.svg"
@module external discordSvg: string = "./discord.svg"
@module external coinmarketcapWhiteSvg: string = "./coinmarketcap-white.svg"
@module external coingeckoSvg: string = "./coingecko.svg"

//Ledger
@module external ledgerCosmosLightIcon: string = "./ledger-cosmos-light.svg"
@module external ledgerBandChainLightIcon: string = "./ledget-band-light.svg"
@module external ledgerCosmosDarkIcon: string = "./ledger-cosmos-dark.svg"
@module external ledgerBandChainDarkIcon: string = "./ledger-band-dark.svg"

//Toggle
@module external sunIcon: string = "./sun-icon.png"

// Loading
@module external loadingCircleLight: string = "./loading-circle-light.png"
@module external loadingCircleDark: string = "./loading-circle-dark.png"

//IBC
@module external ibcIcon: string = "./tx-ibc-icon.svg"
