name: Cosmoscan Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: 'yarn'
          
      - name: Cache node_modules
        id: scan-node-modules-cache
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.OS }}-scan-test-${{ hashFiles('**/yarn.lock') }}
          
      - name: Yarn install deps with node_modules cache
        run: |
          yarn install --frozen-lockfile
          
      - name: Run yarn build
        run: yarn build
        env:
          RPC_URL: "https://d3n.bandprotocol.com/rest"
          GRAPHQL_URL: "wss://d3n.bandprotocol.com/v1/graphql"
          NETWORK: "GUANYU38"
      
      - name: Run install cypress
        run: yarn cypress install

      - name: Run yarn test
        run: yarn test

      - name: Run yarn integration-test
        run: yarn integration-test
